<a href="https://colab.research.google.com/github/sky16k/MDS/blob/main/MDS02_HW_%D0%A9%D0%B5%D0%B4%D1%80%D0%B8%D0%BD%D0%BE%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

####текст

In [ ]:
# комментарий эксперта
'''

'''

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


####программа

In [1]:
import numpy as np

In [3]:
### YOUR CODE HERE
A=np.reshape(np.arange(1, 10),(3,3))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
e=np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
B=A+np.eye(3)
B

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [8]:
B@np.array([1,2,3])

array([15., 34., 53.])

In [9]:
B.T

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [10]:
np.linalg.inv(B)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

####текст

In [ ]:
# комментарий эксперта
'''

'''

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



####программа

In [11]:
### YOUR CODE HERE
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [12]:
eig = np.linalg.eig(m)
eig

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [13]:
eig_values = eig[0]
print('Собственные значения:')
eig_values

array([1., 4.])

In [21]:
eig_m = eig[1]
eig_m

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [24]:
eig_vecs=eig_m.T
eig_vecs[0]=eig_vecs[0]/eig_vecs[0,1]
eig_vecs[1]=eig_vecs[1]/eig_vecs[1,1]


Собственные вектора:


(array([-2.,  1.]), array([1., 1.]))

In [ ]:
print('Собственные вектора:')
eig_vecs[0],eig_vecs[1]
# eig_vecs

### Задание 3


####текст

In [ ]:
# комментарий эксперта
'''

'''

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

####программа

In [105]:
### YOUR CODE HERE
for k in range(0,100):
    np.random.seed=k
    for i in range(0,100):
        A = np.array(np.random.random(9)//0.1)
        A = A.reshape(3,3)
        if (np.linalg.det(A) == 1) and (0 not in A):
            print(k,i,A)
            break


4 63 [[4. 5. 9.]
 [1. 1. 5.]
 [2. 2. 9.]]
13 79 [[3. 4. 1.]
 [3. 3. 1.]
 [4. 7. 1.]]
92 55 [[1. 1. 2.]
 [4. 6. 9.]
 [4. 5. 9.]]


In [102]:
A = np.array([[1,1],[2,3]])
np.linalg.det(A)

1.0

In [107]:
A = np.array([[4. ,5. ,9.],
              [1. ,1. ,5.],
              [2. ,2. ,9.]])
np.linalg.det(A)

1.0